name: C/C++ CI

on:
  push:
    branches: [ dense_map ]
  pull_request:
    branches: [ dense_map ]
    
env:
  BUILD_TYPE: Release
  
jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          package_manager: "apt-get"

        - os: ubuntu-18.04
          package_manager: "apt-get"

        - os: ubuntu-16.04
          package_manager: "apt-get"

    steps:
    - name: Checkout ORB_SLAM2e
      uses: actions/checkout@v2
    
    - name: Checkout Pangolin
      uses: actions/checkout@v2
      with:
        path: ${{runner.workspace}}/pangolin
        repository: 'stevenlovegrove/Pangolin'
        
    - name: Configure CMake Pangolin
      working-directory: ${{runner.workspace}}/pangolin
      run: |
        mkdir -p build && cd build
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        
    - name: Build Pangolin
      working-directory: ${{runner.workspace}}/pangolin/build
      run: cmake --build . --config $BUILD_TYPE
      
    - name: Build ORB_SLAM2e
      working-directory: ${{runner.workspace}}
      run: ./build.sh
        
      
